name: Build

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  # The whole point of the setup job is that we want to set variables once
  # that will be consumed by multiple subsequent jobs.
  setup:
    runs-on: codebuild-gentoo-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 1440
    outputs:
      tarball: ${{ steps.setup.outputs.tarball }}
      log: ${{ steps.setup.outputs.log }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Gentoo Build
        id: setup
        shell: bash
        run: | 
          sudo apt install -y pv
          sudo chmod a+x gentoo-setup.sh
          sudo ./gentoo-setup.sh | tee build.log
          
          echo "tarball=`find /mnt/stage3*.tar.xz`" >> $GITHUB_OUTPUT
          echo "config=/mnt/gentoo/etc/portage/make.conf" >> $GITHUB_OUTPUT
          echo "log=`find build.log`" >> $GITHUB_OUTPUT
      - name: Upload Log
        if: steps.setup.outputs.log
        uses: actions/upload-artifact@v4
        with:
          name: "LogFile"
          path: |
            ${{ steps.setup.outputs.log }}
      - name: Upload Configure
        if: steps.setup.outputs.log
        uses: actions/upload-artifact@v4
        with:
          name: "Configures"
          path: |
            ${{ steps.setup.outputs.config }}
      - name: Upload tarball
        if: steps.setup.outputs.tarball
        uses: actions/upload-artifact@v4
        with:
          name: "Stage3Package"
          path: |
            ${{ steps.setup.outputs.tarball }}
